
INSERT INTO Attractions (Name, Description, Localization, City, State) VALUES ('Serra do Divisor', 'Parque nacional', 'Acre, Brasil', 'Rio Branco', 'Acre');
INSERT INTO Attractions (Name, Description, Localization, City, State) VALUES ('São Miguel dos Milagres', 'Praia de São Miguel dos Milagres', 'Alagoas, Brasil', 'São Miguel dos Milagres', 'Alagoas');
INSERT INTO Attractions (Name, Description, Localization, City, State) VALUES ('Montanhas de Tumucumaque', 'O maior parque de floresta tropical do mundo', 'Amapá, Brasil', 'Serra do Navio', 'Amapá');
INSERT INTO Attractions (Name, Description, Localization, City, State) VALUES ('Arquipélago de Anavilhanas', 'Arquipélago do Rio Negro', 'Amazonas, Brasil', 'Uarini', 'Amazonas');
INSERT INTO Attractions (Name, Description, Localization, City, State) VALUES ('Praia da Comboinha', 'Praia localizada no litoral baiano', 'Bahia, Brasil', 'Itacaré', 'Bahia');
INSERT INTO Attractions (Name, Description, Localization, City, State) VALUES ('Jijoca de Jericoacoara', 'Lagoa de água doce', 'Ceará, Brasil', 'Jericoacoara', 'Ceará');
INSERT INTO Attractions (Name, Description, Localization, City, State) VALUES ('Chapada Imperial', 'Trilhas e cachoeiras', 'Distrito Federal, Brasil', 'Brasília', 'Distrito Federal');
INSERT INTO Attractions (Name, Description, Localization, City, State) VALUES ('Caparaó', 'Serra, o terceiro pico mais alto do Brasil', 'Vale Verde Zona Rural', 'Dores do Rio Preto', 'Espírito Santo');
INSERT INTO Attractions (Name, Description, Localization, City, State) VALUES ('Chapada dos Veadeiros', 'Dezenas de cachoeiras', 'Goiás, Brasil', 'Alto Paraíso de Goiás', 'Goiás');
INSERT INTO Attractions (Name, Description, Localization, City, State) VALUES ('Lençois Maranhenses', 'Região de dunas brancas com lagoas azuis', 'Maranhão, Brasil', 'Barreirinhas', 'Maranhão');
INSERT INTO Attractions (Name, Description, Localization, City, State) VALUES ('Chapada dos Guimarães', 'Trilhas', 'Mato Grosso, Brasil', 'Chapada dos Guimarães', 'Mato Grosso');
INSERT INTO Attractions (Name, Description, Localization, City, State) VALUES ('Rio Sucuri', 'Um dos 10 rios de água doce mais cristalinos do mundo', 'Mato Grosso do Sul, Brasil', 'Bonito', 'Mato Grosso do Sual');
INSERT INTO Attractions (Name, Description, Localization, City, State) VALUES ('Represa de Furnas', 'Rios e Montanhas', 'Minas Gerais, Brasil', 'Capitólio', 'Minas Gerais');
INSERT INTO Attractions (Name, Description, Localization, City, State) VALUES ('Alter do Chão', 'Praias de águas doces', 'Pará, Brasil', 'Santarém', 'Pará');
INSERT INTO Attractions (Name, Description, Localization, City, State) VALUES ('Cabaceiras', 'Paisagens de formações rochosas', 'Paraíba, Brasil', 'Cabaceiras', 'Paraíba');
INSERT INTO Attractions (Name, Description, Localization, City, State) VALUES ('Cataratas do Iguaçu', 'Quedas do Rio Iguaçu', 'Paraná, Brasil', 'Foz do Iguaçu', 'Paraná');
INSERT INTO Attractions (Name, Description, Localization, City, State) VALUES ('Vale do Catimbau', 'Parque nacional brasileiro do estado de Pernambuco', 'Pernambuco, Brasil', 'Buíque', 'Pernambuco');
INSERT INTO Attractions (Name, Description, Localization, City, State) VALUES ('Praia do Pontal', 'Praia localizada no município de Paraty', 'Rio de Janeiro, Brasil', 'Rio de Janeiro', 'Rio de Janeiro');
INSERT INTO Attractions (Name, Description, Localization, City, State) VALUES ('Aparados da Serra', 'Florestas de araucárias, cascatas e paredões de granito', 'Rio Grande do Sul, Brasil', 'Cambará do Sul', 'Rio Grande do Sul');
INSERT INTO Attractions (Name, Description, Localization, City, State) VALUES ('Parque Estadual Corumbiara', 'Biomas de Cerrado, Pantanal e Floresta Amazônica', 'Rondônia, Brasil', 'Corumbiara', 'Rondônia');
INSERT INTO Attractions (Name, Description, Localization, City, State) VALUES ('Monte Roraima', 'Tepui', 'Roraima, Brasil', 'Serra de Pacaraima', 'Roraima');
INSERT INTO Attractions (Name, Description, Localization, City, State) VALUES ('Guarda do Embaú', 'Praia localizada no município de Paulo Lopes', 'Santa Catarina, Brasil', 'Paulo Lopes', 'Santa Catarina');
INSERT INTO Attractions (Name, Description, Localization, City, State) VALUES ('Cavernas do PETAR', 'Parque Estadual Turístico do Alto Ribeira', 'São Paulo, Brasil', 'Iporanga', 'São Paulo');
INSERT INTO Attractions (Name, Description, Localization, City, State) VALUES ('Cânion do Xingó', 'Oásis', 'Sergipe, Brasil', 'Canindé de São Francisco', 'Sergipe');
INSERT INTO Attractions (Name, Description, Localization, City, State) VALUES ('Parque Nacional do Jalapão', 'Formações rochosas, lagoas e dunas', 'Tocantins, Brasil', 'Mateiros', 'Tocantins');